name: Clang Format Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: clang-format --dry-run --Werror src/**/*.cpp include/**/*.h

  autoformat:
    runs-on: ubuntu-latest
    if: ${{ failure() }}   # Solo se ejecuta si el job anterior falla
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Autoformat with clang-format
        run: |
          clang-format -i src/**/*.cpp include/**/*.h
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/**/*.cpp include/**/*.h
          git commit -m "Apply clang-format automatically"
          git push
